import type {
  AppEnvironment,
  AttributionSnapshot,
  ConsentRecord,
  ExperimentState,
  FunnelKind,
  FunnelVersionState,
  OutboxEvent,
  SubmissionState,
  Touchpoint,
  TrackingEvent,
  TrafficKind,
} from '@am/domain';
import type {
  Answers,
  FunnelSpec,
  MultiStepFormSpec,
  QualificationOutcome,
} from '@am/funnel-schema';

/**
 * The persistence port of the public funnel runtime.
 *
 * Every route handler and every page in this app talks to storage through this
 * interface and nothing else. Today it is backed by `fixture-store.ts` (in
 * memory, seeded from `@am/funnel-schema`'s fixtures) so the runtime works end
 * to end; the lead wires the same interface to `@am/db` without touching a
 * single route.
 *
 * Three properties the implementation must preserve, because the routes rely on
 * them rather than re-checking:
 *
 * 1. **Published versions are immutable.** `loadPublishedFunnelBySlug` may only
 *    ever return a `PUBLISHED` version; a draft must never leak onto a live
 *    slug (AGENTS.md rule 6).
 * 2. **`acceptSubmission` is one transaction.** The submission, its attribution
 *    snapshot and *all* outbox rows are written together or not at all. That is
 *    what makes "a HubSpot outage never loses a lead" true without a
 *    distributed transaction.
 * 3. **`acceptSubmission` is idempotent on `submissionAttemptId`.** Concurrent
 *    identical attempts collapse onto exactly one submission and the same id is
 *    returned to every caller.
 */

/* -------------------------------------------------------------------------- */
/* Funnel versions                                                             */
/* -------------------------------------------------------------------------- */

export interface FunnelExperimentArm {
  armId: string;
  /** Share of traffic; weights are normalised, so they need not sum to 1. */
  allocation: number;
  /** The funnel version this arm serves. */
  funnelVersionId: string;
}

export interface FunnelExperimentRecord {
  experimentId: string;
  state: ExperimentState;
  /** `experiments.assignment_salt`, frozen while the experiment is RUNNING. */
  assignmentSalt: string;
  arms: FunnelExperimentArm[];
}

export interface FunnelVersionRecord {
  funnelId: string;
  funnelVersionId: string;
  /** Public path segment under `/f/`. */
  slug: string;
  kind: FunnelKind;
  state: FunnelVersionState;
  /** ISO-8601; `null` while the version is still a draft. */
  publishedAt: string | null;
  spec: FunnelSpec;
  /** The published form version this funnel serves, when it has one. */
  formVersionId: string | null;
  /** The running funnel experiment this version participates in, if any. */
  experiment: FunnelExperimentRecord | null;
}

export interface PublishedFormRecord {
  formId: string;
  formVersionId: string;
  state: FunnelVersionState;
  publishedAt: string | null;
  spec: MultiStepFormSpec;
}

/* -------------------------------------------------------------------------- */
/* Form instances and progress                                                 */
/* -------------------------------------------------------------------------- */

export interface CreateFormInstanceInput {
  visitorId: string;
  sessionId: string;
  funnelId: string;
  funnelVersionId: string;
  formId: string;
  formVersionId: string;
  environment: AppEnvironment;
  trafficKind: TrafficKind;
  experimentId: string | null;
  experimentArmId: string | null;
  /** ISO-8601 start of the instance. */
  startedAt: string;
  /**
   * The touch this instance was opened from. Appended to the visitor's touch
   * list; an existing acquisition touch is never rewritten.
   */
  touch: Touchpoint | null;
}

export interface FormInstanceRecord {
  formInstanceId: string;
  visitorId: string;
  sessionId: string;
  funnelVersionId: string;
  formVersionId: string;
  experimentId: string | null;
  experimentArmId: string | null;
  environment: AppEnvironment;
  trafficKind: TrafficKind;
  startedAt: string;
  lastActivityAt: string;
  lastStepId: string | null;
  submitted: boolean;
}

export interface RecordStepProgressInput {
  formInstanceId: string;
  stepId: string;
  /** ISO-8601 business time of the step transition. */
  occurredAt: string;
  /** True once the visitor left the step with a valid answer. */
  completed: boolean;
}

/* -------------------------------------------------------------------------- */
/* Submissions                                                                 */
/* -------------------------------------------------------------------------- */

export interface SubmissionQualification {
  outcome: QualificationOutcome;
  score: number;
  matchedRuleIds: string[];
  reasonCodes: string[];
}

/**
 * The row to write. `submissionId` is generated by the caller so that the
 * attribution snapshot and the deterministic CAPI event id can be built inside
 * the same unit of work; on a duplicate attempt the store discards it and
 * returns the id it already stored.
 */
export interface SubmissionDraft {
  submissionId: string;
  /** Client-generated attempt id. The idempotency key. */
  submissionAttemptId: string;
  formInstanceId: string;
  funnelId: string;
  funnelVersionId: string;
  formId: string;
  formVersionId: string;
  visitorId: string;
  sessionId: string;
  environment: AppEnvironment;
  trafficKind: TrafficKind;
  state: SubmissionState;
  qualification: SubmissionQualification;
  /** The result variant the visitor was shown, when the spec selected one. */
  resultVariantId: string | null;
  /** Qualification answers — safe for reporting and rollups. */
  answersNonPii: Answers;
  /** Personal data — stored separately, subject to the retention policy. */
  answersPii: Answers;
  /** Operational values (honeypot, timings, hidden context). */
  answersOperational: Answers;
  consent: ConsentRecord;
  /** 0 (clean) … 100 (certain spam). */
  riskScore: number;
  submittedAt: string;
}

export interface AcceptSubmissionInput {
  submission: SubmissionDraft;
  /** Immutable, frozen at submit. Its `submission_id` is `submission.submissionId`. */
  attribution: AttributionSnapshot;
  /** HubSpot sync + Meta CAPI initial lead. Written in the same transaction. */
  outbox: readonly OutboxEvent[];
}

export interface AcceptSubmissionResult {
  submissionId: string;
  /** False when an identical attempt had already been accepted. */
  created: boolean;
  outboxEventIds: string[];
}

/* -------------------------------------------------------------------------- */
/* The port                                                                    */
/* -------------------------------------------------------------------------- */

export interface FunnelStore {
  /** The live version of a public slug. Never returns a draft. */
  loadPublishedFunnelBySlug(slug: string): Promise<FunnelVersionRecord | null>;

  /** Any version, in any state. Preview only — never reachable from `/f/`. */
  loadFunnelVersion(funnelVersionId: string): Promise<FunnelVersionRecord | null>;

  /** The published form document a funnel version points at. */
  loadPublishedFormSpec(formVersionId: string): Promise<PublishedFormRecord | null>;

  /**
   * Opens — or re-opens — a form instance. Idempotent per
   * (visitor, session, form version): a reload must not fork the funnel into two
   * instances, which would double every step-level metric.
   */
  createFormInstance(input: CreateFormInstanceInput): Promise<FormInstanceRecord>;

  recordStepProgress(input: RecordStepProgressInput): Promise<void>;

  /** Appends an observed touch to the visitor's history. */
  recordTouch(touch: Touchpoint): Promise<void>;

  /** The visitor's touches, oldest first. Input to `buildAttributionSnapshot`. */
  listTouches(visitorId: string): Promise<Touchpoint[]>;

  /**
   * Writes submission + attribution snapshot + outbox rows atomically, keyed on
   * `submission.submissionAttemptId`.
   */
  acceptSubmission(input: AcceptSubmissionInput): Promise<AcceptSubmissionResult>;

  /** Persists validated analytics events. Returns how many rows were written. */
  recordEvents(events: readonly TrackingEvent[]): Promise<number>;

  /** Read side, for the runbook and the tests that prove a lead was queued. */
  listOutboxForSubmission(submissionId: string): Promise<OutboxEvent[]>;
}
